### ISSUE TITLE
License File Missing

### ISSUE THREAD

**Issue by karanmarjara** [parzh/create-package-typescript#12]
Can you please add the license file to this repo. Thanks.

**Comment by parzhitsky** [comment]
Hey! Sure, I can do that. In the meantime, there's a [`license` field in `package.json`](https://github.com/parzh/create-package-typescript/blob/master/package.json#L6), would that suffice?

**Comment by parzhitsky** [comment]
@josh-yoder-vive Problem?

**Comment by josh-yoder-vive** [comment]
> @josh-yoder-vive Problem?

No, not at all, I apologize...I didn't even realize I'd hit the thumb down, meant to hit the thumbs up.  My bad.

**Comment by parzhitsky** [comment]
Okay, no worries. Just be informed that this somehow also slipped to #7, #4, – but that's probably a GitHub bug, right?
